[book]
authors = ["MarcusWentz"]
language = "en"
multilingual = false
src = "src"
title = "⚙️ template-testing ⚙️"

[output.html]
git-repository-url = "https://github.com/MarcusWentz/mdbook-template"
edit-url-template =  "https://github.com/MarcusWentz/mdbook-template/edit/main/src/README.md"
mathjax-support = true
additional-js =  ["src/static/solidity.min.js"]
additional-css = ["src/static/tabs4.css"]